### ISSUE TITLE
Persona precessing in seq2seq

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#1048]
In `projects.personachat.persona_seq2seq.py` line `1604` `observation['persona'] = self.persona_given` is set. `self.persona_given` however is cleared before in lines `1586` and `1589`, respectively. So accordingly, when I interact with the model and give it like `your persona: I like pizza\n what do you like` it will put `I like pizza` in the observation['persona']. In the next iteration, `observation['persona']` will be cleared as their is no persona to observe. 

However, I am not sure where the observed persona is handed on to the next interaction iteration as this bit of code is called right from `parlai.core.worlds.py` line `242` if I am not mistaken. This is not happening when I set `usepreviousdialog: True` as in lines `1584` and `1585`, all relevant entries are usually cleared from `self.episode_done == True`. What is the intention behind `episode_done`?

And asked the other way around, how do I make sure a certain persona given at the beginning of a conversation is influencing all the outputs throughout a conversation?

https://github.com/facebookresearch/ParlAI/blob/46042a58f8884cbe379f4f6616a92cf84355143b/parlai/core/worlds.py#L237-L245

https://github.com/facebookresearch/ParlAI/blob/46042a58f8884cbe379f4f6616a92cf84355143b/projects/personachat/persona_seq2seq.py#L1575-L1612

**Comment by uralik** [comment]
if you want be sure what is exact input to the model during the training (which is not observation only usually) - you can check here:
https://github.com/facebookresearch/ParlAI/blob/46042a58f8884cbe379f4f6616a92cf84355143b/projects/personachat/persona_seq2seq.py#L868

so whatever is in xs will be used as the input to your model. Consider checking that at every time step and you will get the intuition how the input is constructed from observation, history etc.

**Comment by christqoh** [comment]
Thank you for coming back at me @uralik. In my case that'd be https://github.com/facebookresearch/ParlAI/blob/b980e704cb3590f399b3852e3ce39e14f37404b2/projects/personachat/persona_seq2seq.py#L2276
Having xs as the input to the model makes sense. However, the last part of the code excerpt is `= self.batchify(observations)` so if I am not mistaken, whatever is not in the observations will not be converted for the model?! Where does the history come in?

**Comment by uralik** [comment]
Yes in case of this agent - dialogue history and persona profile injection is handled here:
https://github.com/facebookresearch/ParlAI/blob/b980e704cb3590f399b3852e3ce39e14f37404b2/projects/personachat/persona_seq2seq.py#L997-L1019

but be aware that this is not true for other agents, some agents implement another function to maintain the dialogue history.

So in case of your agent you should check that your agent has this attribute self.usepreviousdialog is set, otherwise profile will not be in your observation.

**Comment by christqoh** [comment]
I got the idea of that, however when I run `python projects/convai2/baselines/profilememory/interactive.py --attention general --personachat-useprevdialog` I never arrive in lines 1594 to 1599. The code follows 1588 and resets the `persona_given`.

Example: 
Iteration 1:
"your persona: I am a robot\n what are you?"
""

https://github.com/facebookresearch/ParlAI/blob/b980e704cb3590f399b3852e3ce39e14f37404b2/projects/personachat/persona_seq2seq.py#L1575-L1612

**Comment by christqoh** [comment]
I got the idea of that, however when I run `python projects/convai2/baselines/profilememory/interactive.py --attention general --personachat-useprevdialog` I never arrive in lines 1594 to 1599. The code follows 1588 and resets the `persona_given` as indicated in my original post. 

Example conversation:
User: "your persona: I am a robot\n what are you?"
Observation: {'id': 'localHuman', 'episode_done': False, 'label_candidates': None, 'text': ' what are you?', 'persona': 'I am a robot\n'}
[Seq2Seq]: i am a robot . i love robot limbs
User: "what are you?"
observation: {'id': 'localHuman', 'episode_done': False, 'label_candidates': None, 'text': 'what are you?', 'persona': ''}
[Seq2Seq]: i am a professional painter . what do you do ?



https://github.com/facebookresearch/ParlAI/blob/b980e704cb3590f399b3852e3ce39e14f37404b2/projects/personachat/persona_seq2seq.py#L1575-L1612

**Comment by emilydinan** [comment]
Hi @christqoh -- if you just get rid of this [line] (https://github.com/facebookresearch/ParlAI/blob/b980e704cb3590f399b3852e3ce39e14f37404b2/projects/personachat/persona_seq2seq.py#L1589) it should be okay.  (It's possible that this code was here because in previous iterations of the dataset the personas were fed in at every turn. I'm not sure though.) Since for the current version of the dataset the personas are only fed in at the first turn, you are correct in that you should get rid of this line. The resetting of `self.persona_given` after `self.episode_done == True`, is correct since the personas are only relevant for a given episode (and presumably there will be new personas for the next episode).

**Comment by christqoh** [comment]
Thank you @emilydinan, I was suspecting something like this... Just feeding every turn would've been my brute force approach :D

I still have one question: what does the `episode_done` stand for exactly and when is it changed?

**Comment by christqoh** [comment]
works for me, thank you @emilydinan
