### ISSUE TITLE
convai2 synthetic training data

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#1148]
I've started testing out training with a synthetically created dataset based on the original training data. Under the rules of the competition does this have to be released? I have no problem with releasing it but with the whole synthetic creation pipeline it is rather subject to change over time. 

Another point I'm curious to see clarification on. If the data itself is augmented, for example with token level features, does this also need to be released?

I'm assuming as well when it says `Hence, all entrants are expected to work on publicly available data or release the data they use to train.` that this means released before the end of the competition.

**Comment by emilydinan** [comment]
Hi @Henry-E! We expect you to release the data, but you do not have to release it until after the competition. In terms of augmenting your data with token level features, as the competition website states "We will require that the winning systems also release their training code so that their work is reproducible (although we also encourage that for all systems)." Therefore, we hope that you release your training code after the competition but only require it in the event that your system wins.

**Comment by Henry-E** [comment]
Ok great, thanks for the clarification
