### ISSUE TITLE
Every response in corpus is a possible candidate?

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#134]
In the dialogue corpuses the examples appear to contain every possible response as a possible candidate. What's the general logic behind this or is it a byproduct of using `fbdialog_teacher`'s `setup_data` function?

> [opensubtitles]: Everybody\' s a little nervous their first night in show business .
[labels: You just do what we rehearsed and everything will be fine .]
[cands:  - I\' m packing right now .| Then Pearl Harbor happened and everything changed .| Well , then maybe you can explain to me why that robust woman is eating my girlfriend\' s din ...| This postmark is too faint to read .| - It\' s not attached to the adjacent bulldings .| **...and 741300 more**]
   [RepeatLabelAgent]: You just do what we rehearsed and everything will be fine 

> [cornell_movie]: Edward, did you hear me?
[labels: I'm here.]
[cands: No, Kringelein, not tired, -- just --  Well -- well --|Now he's gone and made me fall in love with him, which I never wanted to do. I told him that.|By killing them?|I lost it. I lose everything.|Lynette, I told you already, it won't work.| **...and 97145 more**]
   [RepeatLabelAgent]: I'm here.

On a side note I'm making my own task which isn't a dialogue but can follow the format of one fairly easily. Putting the data into fb format and inheriting from `fbdialog_teacher` seems to be the simplest approach.

**Comment by jaseweston** [comment]
Yes, we made all of them candidates, the logic being that this includes the right one, plus a bunch of stuff that is plausible (of the same distribution). We could just do that for validation and test and not train, though.. (I think some datasets made that choice, but the user's agent can do what they want in train, so it doesn't make too much difference).

Yes, using fbdialog_teacher is the simplest approach if your data is of a fixed form that you can just save as a text file. But it's not that hard to do otherwise, either..

**Comment by Henry-E** [comment]
Great, well I have a buggy task working with display_data.py now at least. Onto training.
