### ISSUE TITLE
will you give the best scripts to train the typical model such as seq2seq or transformer on each task/dataset in the ParlAI?

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#1468]
In my view, this can facilitate the research of dialogue systems.

**Comment by stephenroller** [comment]
Hi @zhaoguangxiang. One goal we have in the next few weeks is to actively beef up our model zoo. These models will come with the hyperparameters used to train them.

**Comment by jaseweston** [comment]
Yes, the goal is to have in parlai/projects tracking of best efforts on
these tasks.
For convai2 for example we have this here:
https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2
As Stephen says we do have things we are going to release into the model
zoo soon.
Note that this is also a community effort, where others can check in their
best models, as there are many tasks...

**Comment by stephenroller** [comment]
Hi @zhaoguangxiang. While the zoo is never fully complete, there are [some improvements](http://parl.ai/static/docs/zoo.html) from last week. Most of these have the training scripts available.

**Comment by stephenroller** [comment]
(Feel free to reopen for specific requests or additional questions)

**Comment by JohannesTK** [comment]
Have you thought of having different hyperparameters sets like [Tensor2Tensor](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L1546)? I.e. transformer_base, transformer_tiny, etc. Feels like this would vastly speed up the experimentation and training on new datasets because it would take out a lot of the guessing game.
