### ISSUE TITLE
How do I train a large seq2seq model on opensubtitles across two GPUs? 

### ISSUE THREAD

**Issue by martinritchie** [facebookresearch/ParlAI#1500]
Hey, 

1. How do I train a large seq2seq model on the opensubtitles task across two GPUs? Is it somthing like: 
`python -m parlai.scripts.multiprocessing_train \
    -m seq2seq \
    -t opensubtitles
`
and so on?
2. Is it possible to set both the training and validation data to: stream? 

Thank you.

**Comment by stephenroller** [comment]
1. Yes, exactly. If you have access to a slurm environment, I recommend using distributed_train instead of multiprocessing train, but that works well. opensubtitles is *super* big though and so you might need a bit more than 2 GPUs, and you might benefit from using pytorch data teacher.
2. Yes, validation is by default streaming. Passing the `--datatype train:stream` flag will ensure that training is also streaming.

Please feel free to repoen if you have more questions.
