### ISSUE TITLE
[Data question]: Same data  in ConvAI2 dataset for validation and test

### ISSUE THREAD

**Issue by jazzminewang** [facebookresearch/ParlAI#1604]
When running, ```python examples/display_data.py --task convai2 --datatype test``` as described on the ConvAI challenge page, the output specifies: 
```[ loaded 1000 episodes with a total of 7801 examples ]. ```. 
However, running ```python examples/display_data.py --task convai2 --datatype valid``` produces the exact same data and output. 

1. Since the paper specifies that there are 1000 dialogues for validation, and 968 for test - is the test dataset public yet? [#1107].
2. I assume here that episodes == dialogues. What does examples reference?

**Comment by stephenroller** [comment]
This is intentional. As I recall, the convai2 test dataset will never be publicly released, but @emilydinan should confirm.

**Comment by emilydinan** [comment]
Hi @jazzminewang -- this is intentional. If you look at the code, it prints out a warning ` UserWarning: WARNING: Test set not included. Setting datatype to valid.`

1. The test set is not public and we do not have currently plans to release it.
2. Episodes refer to a conversation/dialogue in the dataset. Examples refer to single turn exchanges within the episode. If you want to visualize this, running `python examples/display_data.py -t convai2 -ne 20 -dt valid`, you'll see examples are separated `~~` and episodes are separated by `- - - - - - - - - - - - - - - - - - - - -`. For more information see this tutorial: https://parl.ai/docs/tutorial_task.html

Closing for now, feel free to reopen if you have more questions!
