### ISSUE TITLE
What version of react and react-dom is the Sandbox Mturk using?

### ISSUE THREAD

**Issue by jazzminewang** [facebookresearch/ParlAI#1626]
I'm getting an interesting error "Unable to find node on an unmounted component in React 16.0.0" when following the README.md in overriding the live chat frontend with custom components (https://parl.ai/docs/tutorial_mturk.html#custom-frontend-components). 

The issue seems to be react version compatibility - could the react and react-dom versions be added to mturk/package.json? 

https://github.com/Pomax/react-onclickoutside/issues/231#issuecomment-333174275

I'm not seeing this error when doing local development (https://parl.ai/docs/tutorial_mturk.html#running-the-parlai-mturk-webapp) so I'm assuming it's some sort of incompatibility with pre-compiled React code vs my own. Only seeing it when I run my own task's ```run.py``` in sandbox mode. 

Apologies for submitting so many issues! Please let me know if in general the issues I submit should be better documented/better articulated.

**Comment by JackUrb** [comment]
Hi @jazzminewang - Thanks for opening an issue! I actually haven't tested the custom component flow particularly rigorously, so it's very possible that there's an issue with versioning. If you can get the versions to be the same and that works, I'll be sure to incorporate the versioning properly into the upcoming upgrades to the platform.

**Comment by jazzminewang** [comment]
Thanks @JackUrb. Do you know what version of React and React-dom the pre-compiled Sandbox is running? It's not in the package.json.

Also - do you have any template code for adding checkbox/dropdown responses instead of text? Alternatively, do you have any suggestions (eg. which components to best replace, for example) for having a reviewer submit evaluations of multiple dialogue responses at once?  
cc @KoustuvSinha

**Comment by JackUrb** [comment]
I'm not sure what you're referring to when you say "pre-compiled", as everything is compiled in a build step every time you run a task at the moment. 

We do have form components though, introduced in #1542.

**Comment by jazzminewang** [comment]
re: pre-compiled - I'm not seeing changes when I directly edit ```parlai/mturk/core/react_server/dev/components/core_components.jsx``` (I do not intend to actually modify them directly but will replace them as per recommended flow, this is for testing purposes) and then restart the sandbox with  ```python run.py -nc 20 -r 0.05 --sandbox```. That's why I thought it was pre-compiled. Should I be seeing changes if I directly edit that file? (ex. I commented out the entire file and everything rendered properly..)

**Comment by JackUrb** [comment]
Directly editing that file should cause changes to the components on a rebuild unless your task has a `custom.jsx` file that is overriding the component you're changing. One way you can validate this is what's happening is by editing `TaskDescription`, which is a component that appears both on the cover page and inside the task. Below is what happens when I edit `parlai/mturk/core/react_server/dev/components/core_components.jsx` and launch the `qa_data_collection` task.

<img width="1491" alt="Screen Shot 2019-04-14 at 4 21 21 PM" src="https://user-images.githubusercontent.com/1276867/56098734-68be7980-5ed1-11e9-9a05-57089efe5fff.png">
<img width="1474" alt="Screen Shot 2019-04-14 at 4 21 31 PM" src="https://user-images.githubusercontent.com/1276867/56098735-68be7980-5ed1-11e9-984c-4f9df9bf4aff.png">

**Comment by jazzminewang** [comment]
Resolved! I needed to have ```task_config['frontend_version'] = 1```. Thanks so much!
