### ISSUE TITLE
AttributeError when TorchAgent.scheduler doesn't exist.

### ISSUE THREAD

**Issue by qibinc** [facebookresearch/ParlAI#1646]
Hi contributors,

Please have a look at this line:

https://github.com/facebookresearch/ParlAI/blob/85653ee4f04b1236a6f6d32944f5856e54418ccd/parlai/core/torch_agent.py#L1366

If the TorchAgent object doesn't have the 'scheduler' attribute, it'll raise an AttributeError. Does this `getattr` meant to be `hasattr` like the above lines?

**Comment by stephenroller** [comment]
Probably should be `getattr(self, 'scheduler', None)`.

```python-console
>>> class Test(object):
...     foo = "bar"
...
>>> t = Test()
>>> t.foo
'bar'
>>> getattr(t, 'foo')
'bar'
>>> getattr(t, 'foo2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Test' object has no attribute 'foo2'
>>> getattr(t, 'foo2', None)
>>>
```

**Comment by stephenroller** [comment]
Feel free to make a PR.

**Comment by THUcqb** [comment]
Yeah `getattr` definitely works well here but I thought `hasattr` is more suitable here and consistent with the line:

https://github.com/facebookresearch/ParlAI/blob/85653ee4f04b1236a6f6d32944f5856e54418ccd/parlai/core/torch_agent.py#L1347

Could you explain the reason for using `getattr(self, 'scheduler', None)` instead of `hasattr(self, 'scheduler')`?

**Comment by stephenroller** [comment]
Because scheduler is set to `None` when the user opts out of a scheduler

https://github.com/facebookresearch/ParlAI/blob/48db0dbbb235e1a6c5dd5caa7389d79b88b8af84/parlai/core/torch_agent.py#L710-L711

`hasattr` will still trigger when the attribute is set to `None`, but `getattr(attrname, None)` will return `None`, which will fail the if condition.
