### ISSUE TITLE
Evaluation of models very slow - best way to speed up? 

### ISSUE THREAD

**Issue by jazzminewang** [facebookresearch/ParlAI#1698]
Currently, time estimate for running [transformer chatbot](https://github.com/atselousov/transformer_chatbot) (from convai2 challenge) is intractably long - 5 days for test dataset and 2 weeks for training. This is even with changes to batchsize (upped to 64 and 128). Are there any other ways to speed up inference time/logging time? For context, I need the output of the models in order to label them on Mturk.

**Comment by stephenroller** [comment]
So if you’re explicitly using the Lost in Conversation model, I’m not sure how much we’re going to be able to help explicitly, since that code isn’t owned or supported by Parlai. Nonetheless let’s see if we can help.

So if I understand correctly, this model jointly encodes the context and response and so it’s inherently slow and there’s not much that can be done without changing the algorithm. My colleagues have actually just released a new paper describing a much faster method of using BERT:

https://arxiv.org/abs/1905.01969

Using our BERT biencoder (which is already in parlai) will be likely 1000x faster, but it’s a different model.

If you explicitly want the LIC model, you’re best shot is to shard the dataset and parallelize it over many machines. The easiest way to do that is to modify the teacher.

**Comment by stephenroller** [comment]
I’ve been told that I’m wrong and LIC’s model was a generative model, and that it was reasonably performant during the competition.

For posterity, performance improvement discussion their code is ongoing here: https://github.com/atselousov/transformer_chatbot/issues/14.

**Comment by jazzminewang** [comment]
Thank you @stephenroller! :)
