### ISSUE TITLE
Code coverage for unit tests to CircleCI.

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1880]
Right now we have a good starting point of unit tests, but we lack code coverage statistics. @alexholdenmiller had originally hacked together a script which roughly uses coverage.py, but the results are currently inaccessible and not terribly readable anyway.

The task is to find and implement a code coverage solution for ParlAI. It should be run in CircleCI (probably nightly) and be easily accessible to the team. Methods of tracking our code coverage over time would also be appreciated, but is less important.

**Comment by vedantpuri** [comment]
@stephenroller 
I have yet to understand how this would work but do you think [codecov](https://docs.codecov.io/docs/quick-start) be used as a solution?

**Comment by stephenroller** [comment]
Yes that’s actually what I wanted to use

**Comment by vedantpuri** [comment]
Another question:
Should I be using the ```coverage.sh``` script in the repo. Is there any description available for that ?

**Comment by stephenroller** [comment]
Axe the coverage.sh. I think the task should be to get each of the testing setups outputting a [coverage xml file](https://coverage.readthedocs.io/en/coverage-4.3.4/cmd.html) that can be uploaded to codecov. Standing that up would be a big benefit.

I think FB employees are going to have to actually do the hooking up to CodeCov.

**Comment by vedantpuri** [comment]
Yes, I was about to talk to you about the hooking up to codecov. If you could do that, that would be great, and I could try to work on this issue!

**Comment by stephenroller** [comment]
The coverage.py running and outputting the xml file still needs to be done, and can be done without codecov integration.

**Comment by vedantpuri** [comment]
I was trying to work on this and installed and ran coverage in the following way:
```bash
coverage run setup.py test -s tests.suites.unittests -v
```
I piped the output to a file and this is what I get:
[out.txt](https://github.com/facebookresearch/ParlAI/files/3786882/out.txt)

Not sure if this the desired output since this shows coverage for everything in ".egg/" as well. Any tips or suggestions on how to go about this ?

**Comment by stephenroller** [comment]
1. We’re free to add a coverage.py config to this repo. I’d even encourage it.
2. You could do `—omit .eggs` it looks like.

**Comment by stephenroller** [comment]
Also once you get the xml output format, you can use the CODECOV environmental variable like the codecov.io docs say. I added it to the circleci environment.

**Comment by vedantpuri** [comment]
So I started working on this issue, (PR referenced above). As of now I wrote a small config file and ignored everything in ".eggs/" and also all "__init__.py" files. Locally I did try generating the xml file and was successful in doing so but it doesn't seem very informative at first glance. You can have a look at the sample xml file here:
[coverage.xml.zip](https://github.com/facebookresearch/ParlAI/files/3791770/coverage.xml.zip)

I tried generating an HTML and that looks much neater instead, it creates a whole folder with a bunch of files with a much better and easy to understand UI. An example HTML output is here:
[htmlcov.zip](https://github.com/facebookresearch/ParlAI/files/3791777/htmlcov.zip)

I personally thought the HTMLmight be great since you can click on links and do a whole bunch of stuff, let me know what you think and I can implement whichever you feel is better suited!

**Comment by stephenroller** [comment]
From offline communication: HTML will be generated by codecov.io, so we just need the XML files.
