### ISSUE TITLE
Switch from print to logging

### ISSUE THREAD

**Issue by klshuster** [facebookresearch/ParlAI#1886]
Currently, ParlAI communicates with a user via print statements, for all sorts of situations: warnings ([example](https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/agents.py#L459)), tracking training progress ([example](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/train_model.py#L682)), general model info ([example](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/language_model/language_model.py#L206)), etc. This is not ideal, as it places the burden on a user to capture the output in order to log any sort of progress.

To remedy this, we'd like to incorporate logging throughout ParlAI using Python's logging module ([here](https://docs.python.org/3/library/logging.html)) as it provides numerous abstractions/handling for various types of things we would like to log (warnings, info, etc). The logging could include a prefix, e.g. including some combination of `<timestamp>|<module>|<filename>|<line>|<log level>`.

An additional ask for this is a unit test that ensures future PRs do not use print statements.

**Comment by vedantpuri** [comment]
Haven't done much work on this yet but I was thinking of having a script in parlai.core that initializes a logger variable and importing this script to any file that prints something and then using the logger variable there. I was thinking of having the logger print to stdout as well as saving the log of that day to a particular file.
The  things I am confused about as of now are:
- How does this work in areas where ```capture_output()``` has been called. I haven't tried this yet but hoping to have the output written to the log file atleast in this case if not stdout (I suspect that is what would happen since it blocks stdout). Any thoughts ?
- Also not sure about how to handle the usage of ```override_print()``` with logging. (```distributed_utils.py```)
- For the testing phase, I was simply hoping to do a regex match on the string in a program like this:
```python
with open(fname) as myFile:
    lines = myFile.readlines()
    for line in lines:
        tokens = line.split()
        for tok in tokens:
            if regex.match(tok):
                break
```
This seems to work but would you know if there would be a better way ?

**Comment by klshuster** [comment]
I think including a logger definition in `parlai.core.utils` would be helpful for this, and you can import/instantiate that logger in appropriate places. I like the idea of printing to stdout and additionally logging to a file (perhaps related to a model file if specified? default log file could be something we need to think about)

To answer your questions:

- `capture_output()` is primarily used in testing, so that our tests do not print to stdout. this should work as is, without you having to change anything (it just captures anything printed to stdout so that our script outputs do not clutter test outputs)
- Good catch - I wouldn't worry about this too much for now, perhaps @stephenroller has more insight here.
- That works, i imagine most of the prints we are worried about come from our `scripts` folder anyway so i'd focus primarily on those (and `core`), but a regex match will help bring up other cases throughout the repo.

**Comment by stephenroller** [comment]
capture_output and override_print should be rewritten to adjust to the logging. Their goal is to  quiet tests and quiet non-primary workers respectively. They can both be updated to simply disable logging.

I'd recommend we not put this in utils, but rather make parlai.core.log. It should have some global methods like `log`, `info`, `warn`, `debug`, and `error` (am i missing any?) We'll replace all the prints with a `log.log()` and slowly adjust the verbosity as we pass over old code.

**Comment by vedantpuri** [comment]
This issue was divided into two parts:
- Implement a logger and deal with edge cases. Done in #2030 
- Switch the project to logging only. TO DO as mentioned in : #2044 

Everything related to this issue shall now be discussed in the issue for the second part.
