### ISSUE TITLE
Wizard of Wikipedia chat with knowledge

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#2012]
**/projects/wizard_of_wikipedia/mturk_evaluation_task** allows me to run a task with a human on one side and a chatbot on the other; while,  **/parlai/mturk/tasks/wizard_of_wikipedia** gives the Wizard knowledge (on the current topic) in the left pane.

I am looking for possibilities of combination of the two. A human and chatbot interaction with suggested sentences available for the human in AMT experiment. How can I achieve this?

**Comment by klshuster** [comment]
The second script you mentioned `parlai/mturk/tasks/wizard_of_wikipedia` pairs two humans; one way i would go about this is simply substituting a model agent in for the one of the humans in that script.

You would need to modify the `run.py` file to allow for a single human to run the task (rather than requiring two), and then modify the `worlds.py` file to sub in a model for the `APPRENTICE` role. You can read through the `mturk_evaluation_task` to see how to get a model working within the mturk framework.

Hope that helps, please post here if you have additional questions.

**Comment by stephenroller** [comment]
Closing but please reopen if there are further questions.
