### ISSUE TITLE
Proper versioning in requirements.txt

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2039]
Look into introducing proper versioning in `requirements.txt`. This is a step in installation, and an important step toward our milestone of proper versioning in ParlAI. See #2013 for an example of where this was problematic.

As a secondary step, this would enable us to use [circleci caching](https://circleci.com/docs/2.0/caching/) to speed up the runtime of unit tests. This should also be introduced.

One rough approach would be to get a shell on a circleci instance and run pip freeze. This should be done *without* the torch installation, unless we manage to resolve issues with #2010 such that `pip install torch` works well.

Assigning to @klshuster to delegate.

**Comment by vedantpuri** [comment]
So I understand that we want to introduce versions in requirements.txt just like you did so recently for nltk. So when you mention pip freeze, is that a way to get all the required versions ? and then update requirements.txt with a ```>=``` of that version.
So running pip freeze would be a one time thing just to get the version right ? Slightly confused about that.
Looking into caching so that once setup.py is run every subsequent job uses the cached libraries, hope I understand that correctly.

**Comment by stephenroller** [comment]
Pip freeze might be enough. It would need to happen from a clean machine and something about torch would need to be removed to ensure the user still can choose which version they want (cpu vs gpu) but this may not be as necessary anymore? Idk. This one needs someone to just dive in and figure out the complications I discovered 4 months ago that caused me not to do this.

**Comment by vedantpuri** [comment]
@stephenroller Can this be closed or do we want to resolve torch versioning first?
