### ISSUE TITLE
[CS5152] Generalized Manager/Agent APIs for Chat Services

### ISSUE THREAD

**Issue by klshuster** [facebookresearch/ParlAI#2079]
# Overview
One of the integrations that ParlAI provides for data collection is through Facebook Messenger (see the docs for more details). To use ParlAI messenger, a user simply needs to define a world structure (similar to how the rest of ParlAI works), in which agents interact with each other via `observe` and `act` functions (again, similar to how the rest of ParlAI works). Given that the worlds are simply ParlAI worlds, there is no reason that one should not be able to extend usage of these worlds beyond just the Messenger case. Thus, the goal of this task is to generalize the Messenger functionality to be able to be used with _any_ chat service. 

## Components of Messenger
ParlAI messenger consists of the following fundamental items:

1. [`MessengerAgent`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/agents.py)
    - each person who messages a page is encapsulated as a `MessengerAgent`. 
    - The `MessengerAgent` class defines the standard `Agent` functions of `observe` and `act`
    - In addition, `MessengerAgent` defines a few more functions for interacting with messenger specifically - e.g., `observe_typing_on`, which shows a user the typing indicator (three dots), and `put_data`, which puts messages on the agent’s message queue.
2. [`MessengerManager`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/messenger_manager.py) : 
    - The `Manager` class keeps track of, and launches, all concurrently running worlds. 
    - Thus, the manager deals with handling users’ sent messages, sending additional messages to the users, starting overworlds, starting task worlds, shutting down worlds, etc.

In order to actually integrate with Messenger, the `Manager` makes use of the following subcomponents:

1. [`MessageSender` ](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/message_sender.py)
    - The `Sender` deals with the actual integration with Messenger, i.e. handles the sending and receiving of messages through the Messenger API
2. [`MessageSocket`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/message_socket.py)
    - The `Socket` is a wrapper around `websocket`, which forwards messages from the server (heroku) to the Manager
    - This is done via instantiating the `MessageSocket` with the `_handle_webhook_event` function from the Manager as the `message_callback`.
3. [`MessengerWorldRunner`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/world_runner.py)
    - The `WorldRunner` is a further abstraction of launching the overworlds and task worlds. 
It specifically deals with concurrently launching and running worlds.

Finally, there is a [`Server`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/messenger/core/server/server.js) class, which is simply the server that is loaded onto heroku, and which forwards the messages via the socket to the Manager.

## Problem Definition
Given the integration that we have with Messenger, it is indeed feasible to abstract out the core components of both the `Agent` and `Manager` (and perhaps the other subcomponents) and define a base `Agent` and `Manager` class. With this abstraction, one could then implement a new integration with another chat service by simply implementing the abstract functions of the base classes. Thus, with this base service, the tasks that we define should be able to be run on _any_ chat service.

Your task is to do the following:

1. [x] Create a base `ChatServiceManager` and `ChatServiceAgent`, which define the APIs for the necessary functions
    - Additionally, provide skeleton definitions of the various subcomponents (`Socket`, `Runner`, and `Sender`); or otherwise indicate how the base classes can use such components.
2. [x] Refactor the Messenger infrastructure to use the base classes.
3. [x] Re-organize the directory structure, such that the root is `chat_service`, with a `core` folder (with the base classes), a `tasks` folder (with the example tasks), and a `services` folder, with implementations for appropriate services (and possible sub-folders)
    - This involves refactoring the tasks (if necessary) to be independent of Facebook Messenger - note that this may only involve moving those tasks out of their current folder into a new one.
4. [x] ~~Implement the following chat services using the base API:~~ (Divided into new issues)
    - ~~Interacting via telnet in a terminal window.~~ (Moved to #2207 )
    - ~~Interacting on your local browser.~~ (Moved to #2208)

**Comment by domrigoglioso** [comment]
For the base `Agent` and `Manager` tasks, should we be defining purely abstract functions or have non-abstract utility functions as well?

**Comment by klshuster** [comment]
1. If there are shared utility functions that you believe would be useful across separate implementations, it would be good to implement them in the base class. And perhaps you can indicate in the function _how_ and _why_ someone would want to override this utility function. Alternatively, if you feel these utility functions (e.g. launching external servers etc.) are better suited in helper classes, feel free to put them there (i.e. if they are implementation/service-agnostic).
2. I think what we want to do here, per @JackUrb's recommendation, is leave the actual implementation of setting up comms/sockets to children of `ChatServiceManager` and the utilization of those comms/sockets to `ChatServiceAgent`. The equivalent for the FB Messenger case would be if the functionality of `MessageSocket` and `MessageSender` were rolled into the `Manager` and `Agent` classes. As for the `Runner`, this can also be simply moved into `ChatServiceManager` or left as a helper class.

**Comment by vedantpuri** [comment]
@klshuster 
Before I make some of these changes and commit wanted to make sure my thinking is in the right direction. (I was finding myself using a huge chunk of code and adding it to the base class and hence wanted to confirm)
- Parsing: I am assuming the same config file type would be used for other chat services too. I wasn’t sure what page_id exactly is (assuming facebook page-id) so wasn’t sure if that will be consistent across other chat services too(under assumption will other char services create a page on facebook for the bot?). If parsing is consistent then we can have the same parse_args function (and _load_model function) and probably define an additional function named ```parse_additional_args``` 
- Agent functions: Since you mentioned we are just abstracting out the type of chat service being used, most of the agent related functions should remain the same like:
    - add_agent_to_pool, remove_agent_from_pool, _get_unique_pool, _handle_message_read (assuming we have a base chatServiceSender with a send_read function), _handle_webhook_event (under page-id assumption), _create_agent (assuming baseAgent), get_agent_state, _get_agent, _on_first_message , check_timeout_in_pool, start_task  
- Other ones that could be pre-implemented in base init_new_state start_new_run _expire_all_conversations shutdown (assuming delete server exists) 
- Need more info on these functions and how they relate to messenger if they do (some of these didn’t have any documentation so found it hard to figure out) _handle_bot_read _confirm_message_delivery _on_new_message get_app_token 
- Some functions pass in the ```message``` parameter. Should we assume/define a standard formate the message should follow for every service ? 
Assuming most of the above is true, it seems like this class should be done last and maybe we should first focus on Socket, Sender and Runner and then come to this. Also, instantiated a README (locally as of now in chat_service) , thinking it might be useful to document a step-by-step way to add a chat-service (this can be done when we try to implement one)
