### ISSUE TITLE
How to limit the overall HIT time

### ISSUE THREAD

**Issue by cloudygoose** [facebookresearch/ParlAI#2091]
Hi, a hopefully quick question, I'm doing convai2_model_eval with my fairseq agent, is there any way to change the limit time of the overall HIT (default 30min )?

Another thing is that I found the response is sometimes very lagging, on my server side I see the response is already outputed, but on the web it shows "waiting for the other person to speak". It seems to be a network issue? It that a known issue?

**Comment by JackUrb** [comment]
For changing the HIT time, you can use [`assignment_duration_in_seconds`](https://github.com/facebookresearch/ParlAI/blob/f933df82d41b2e395fd1f7a0b51675a5aa9a2c83/parlai/mturk/core/mturk_manager.py#L1596) as an option sent to the `MTurkManager` via `opts`. We suggest giving workers much more time than you'd expect them to need, as the timer starts counting down from the moment they accept the task, even if they accept it into their queue rather than working on it immediately.

As far as the occasional lag goes, the `convai2_model_eval` task is built on an older version of the infrastructure that has a bunch of problems (lag included), and is only supported for legacy purposes. We are working on finishing the standards for a new crowdsourcing backend, but it won't be in place until around EOY and updating old tasks to work with it will only follow after then.

**Comment by cloudygoose** [comment]
Thanks! Looking forward to the new stuff!
