### ISSUE TITLE
Do we only have to call soft block once for MTurk?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2147]
Hello, 

I call the following function at the end of `run_conversation` function:

```python
if not opt['is_sandbox']:
               for ag_id in world.soft_block:
                    mturk_manager.soft_block_worker(ag_id)
                    print("Soft blocked worker_id:", ag_id)
```

Is it fine to call it once, or do I have to save a list of workers and consistently call this each time before starting a conversation, and then manually delete our list when we want to end the soft block?

If we only have to call it once, what is the default duration for soft block and how can I change its duration?

Thanks!

**Comment by josharnoldjosh** [comment]
Also, Is this the only other thing we have to do to ensure the `soft block` works?

```
    opt['disconnect_qualification'] = 'disconnect_qualification' # these should automatically be replaced to actual value in underlying code?
    opt['block_qualification'] = 'block_qualification' # these should automatically be replaced?
```

If I'm correct, as long as the keys aren't `None`, they'll be updated with the correct value?

**Comment by JackUrb** [comment]
Soft blocks are handled by assigning a qualification to a worker, so as long as you pass the same string in as the 'block_qualification' for each run, you only need to soft block a worker once. That being said, the string you pass to "block_qualification" needs to be a unique string across all MTurk qualification names. It's likely someone has already registered a qualification called "block_qualification" so that's unlikely to work.

**Comment by stephenroller** [comment]
Question seems answered, closing. Please feel free to reopen if there are follow ups.
