### ISSUE TITLE
Can I use this framework for KB-QA task

### ISSUE THREAD

**Issue by wudapeng268** [facebookresearch/ParlAI#225]
Hello everyone：
I saw this framework support SimpleQuestion WebQuestion, but haven't some examples about KB-QA, so can I use this framework for KB-QA task? thanks for your attention.

**Comment by jaseweston** [comment]
Yes, both those datasets are there, e.g. to look at one of them:

py examples/display_data.py  -t webquestions

we currently do not provide an actual KB to search over because it wasn't
clear if there was a canonical one to use (different papers use different
ones), but we can definitely add a default if you need (or you can do it)

**Comment by wudapeng268** [comment]
As I know, someone who major in KB-QA always use freebase as KB, but when google close freebase, they use FB2M and FB5M as KB.

**Comment by li910802** [comment]
I am also wondering can ParlAI use both KB and QA corpus to train a KBQA model ? @jaseweston

**Comment by jaseweston** [comment]
Certainly you can use the framework yes! I'm just not sure if we have any
models that are any good at it as yet.. DrQA perhaps although it would need
to be slightly modified to work I think
