### ISSUE TITLE
Integration of non-ParlAI trained PyTorch model

### ISSUE THREAD

**Issue by AADeLucia** [facebookresearch/ParlAI#2423]
**Is your feature request related to a problem? Please describe.**
I have a trained PyTorch model and I would like to use ParlAI's amazing interactive mode and easy Mechanical Turk integration. But I would like to do this without having to use ParlAI to develop and train the model.

**Describe the solution you'd like**
A way for my PyTorch model to seamlessly integrate with the ParlAI interactive mode and MTurk.

**Describe alternatives you've considered**
I have tried implementing an HRED model and it is very difficult in ParAI due to the extreme hacking required for the custom data loader and model agent.

**Comment by stephenroller** [comment]
You can always develop an agent from scratch, especially if you don't care about speed with batching:

roughly:
```
from parlai.core.agents import Agent

class MyAgent(Agent):
     def __init__(self, opt, shared):
         self.model = load_my_pytorch_model_here()
     def observe(self, observation):
         self.observation = observation
     def act(self):
          # parse the text from observation['text']
          # store any ongoing state information you might need
          self.history += observation['text']
          response = get_response_generated_by_external_model()
          # make sure to reset the dialogue state
          if observation.get('episode_done', False):
              self.history.clear()
          return {'text': response}
```

Properly implementing sharing can help with efficiency.

Does that help?

**Comment by stephenroller** [comment]
Also I’d be interested in knowing more about your pains with developing within parlai. Is it that it’s too difficult? Is it that you have your own framework already that you would rather use?

If developing in parlai is too cumbersome, what parts are the worst? Is it just getting the data into the system? Is it because the HRED model is particularly hard to slot into our abstractions, or do you feel it’s difficult for all models you want to implement?

I respect your original request that it should be easier to slot in externally trained models, and want to help with that. However, it feels like a failing of parlai that you weren’t excited to utilize the abstractions in the first place: we generally find them easy to work with, but we also know them too deeply to understand about their ease of use.

Your feedback would be *extremely* welcome.

**Comment by Shandilya21** [comment]
Hi,
@stephenroller I agree with your thought. @AADeLucia  Is it very difficult to train or implement models in ParlAI. I guess the above examples agent is simple and easy to follow. what makes you hard to train and implement model such as HRED. Like @stephenroller said I also respect your request that it should be easier to use externally pre-trained models and their integration with ParlAI interactive environment will make it more comfortable to developers. However, why we can't just train models and make use of it. I am working on a problem of personalization in dialog, and find one easy implementation written using ParlAI for reproducing the results.

Your feedback would be highly appreciated.

**Comment by AADeLucia** [comment]
Sorry for the very delayed responses! Yes, the main issue wasn't that ParlAI isn't expandable, it was more about the lack of, well, harder examples. The documentation could definitely be expanded to include more advanced examples, preferably once example for extending each class. 

The other issue was the lack of detailed documentation on how the classes worked together. The code is very very modular, which meant that without knowing exactly where a method came from, you'd basically just have to grep through the source code. Having diagrams on the hierarchy of class extension (e.g. PytorchAgent extends Agent or whatever), would be extremely useful.

**Comment by stephenroller** [comment]
Thanks for your feedback!

**Comment by Shandilya21** [comment]
Thanks for your comment.
