### ISSUE TITLE
integrating blender 90M with other modules

### ISSUE THREAD

**Issue by Ashbajawed** [facebookresearch/ParlAI#2664]
hey we trained and evaluated blender 90M module and its performance was pretty good. but as soon as we integrate it with our personal module (for selective queries ) it burst out like for just "hi" msg its responding "oh , okay . well , i like to play video games and watch netflix . what about you ?" or even worse..

what can be the possible reason for this? 

PS: we have use the interactive_web.py code for integration

**Comment by stephenroller** [comment]
Sounds like it's not generalizing well to your data, and that the personachat/empatheticdialogues is overwhelming it. I'd recommend investing more into making sure it's doing well on your own data via fine tuning and collecting more data. If you haven't already, perhaps try falling back to the raw pushshift.io reddit model, rather than the one already fine-tuned on blended skills.
