### ISSUE TITLE
Chatbot on Questionnaire Data

### ISSUE THREAD

**Issue by hammad26** [facebookresearch/ParlAI#2668]
Hi
I want to make a chatbot on a Questionnaire Data. You can assume its type of surveys data. While answering a question people will be discussing a lot of things. For example:

Q: Suggest some improvements in our service.
Now its an open domain question and people can suggest improvements in any area i.e staff behavior, timings, discounts, giving vouchers, etc.

I want to build a **conversational** agent and then want to ask questions(conversation) on responses of people in a **conversational** way not in question-answer form. The chatbot should be able to understand the context from the previous question and I think PartAI has done that to some reasonable extent.

So, is there some pre-trained model that can serve the above purpose? Also which will be a better approach:
1. fine-tuning only on responses of people
2. fine-tuning on questions with its answers

2nd is not looking a good approach because later on, I want to ask different questions from my chatbot than those which were in the Questionnaire. So, questions in the questionnaire were looking not helpful for model fine-tunning. 

From the given [tasks list](https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/task_list.py) which will be best suitable for this use case? Thanks

**Comment by stephenroller** [comment]
I'm not sure, your case is rather specific and I don't know the details of every dataset in parlai. There are several question answering datasets in the tasks lists, but nothing can substitute data that is actually representative of your task.

Good luck.

**Comment by jnoelvictorino** [comment]
May I add to this question?
I am also thinking of something like this.
Given a list of questions, some questions can be open-ended while some can be answered by yes/no or Likert scale.
Then the agent can probe depending on the response. 

Or at the very least, how to start with a simple questionnaire? It will be great to utilize ParlAI in this aspect to have a more natural conversation rather than simply answering a questionnaire form.
