### ISSUE TITLE
Usage of delete_hits.py MTurk

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/ParlAI#2809]
Hey. 

I have a question related to this Issue (https://github.com/facebookresearch/ParlAI/issues/1215). 

Generally, when I shut down my server, I wait for one or two iterations of "Expiration of unassigned HITs", which successfully deletes the Heroku server and exits.

However, when I run delete_hits.py, I see hundreds of HIT groups, with many active HITs (all in the sandbox). So here are my questions:
 
1) Do active HITs from previous tasks appear as active to workers on MTurk Live?
2) Do I need to do anything about this? If yes, what can I do to delete them now?
3) What is the best way to shut down a task in the middle which has several unassigned HITs?
4) One confusion is this: When I search on workersandbox, I can only see a few active groups which I can confirm correspond to those cases where I had to shut down the system due to some error. i.e. without shutting down Heroku. Do I only need to worry about these HIT groups or all the hundreds of HIT groups that I have not been shutting down completely? How to tackle this at this stage? Everything is in sandbox setup only.

**Comment by stephenroller** [comment]
@JackUrb

**Comment by kushalchawla** [comment]
@JackUrb  Just a reminder for this one. Thanks.

**Comment by JackUrb** [comment]
Hi @kushalchawla. The `delete_hits.py` script is very limited in the data that it is able to pull from MTurk, and hasn't really been updated to handle some of the things they had changed since it was written. As such, it never actually removes HITs, and all of the HITs it finds it considers to be "active" even if they're not. Mephisto handles this better with the [`get_outstanding_hits`](https://github.com/facebookresearch/Mephisto/blob/b5bfe6451186d7dfbeac8831cfe4c82b5ed1f626/mephisto/providers/mturk/mturk_utils.py#L656) and [`expire_and_dispose_hits`](https://github.com/facebookresearch/Mephisto/blob/b5bfe6451186d7dfbeac8831cfe4c82b5ed1f626/mephisto/providers/mturk/mturk_utils.py#L674) methods, which actually remove the HITs from the MTurk server (once they've either been expired or completed and reviewed). To answer your questions more directly:

1. Active HITs as noted in `delete_hits.py` may actually already be expired and have no remaining visible tasks. `delete_hits.py` takes a `--sandbox` argument to query the sandbox server, so depending on that flag it will display live or sandbox hits exclusively.
2. If you haven't gotten messages from workers complaining that you have HITs active that they can't work on, you're likely fine. If not, feel free to use the methods from the Mephisto library to query the HITs and delete them for real. You can use the same mturk client that you get from `parlai` scripts to use the methods in Mephisto's `mturk_utils`.
3. CTRL-C once, then wait for the full duration of the what you've specified for the HIT (`assignment_duration_in_seconds`). After that, you can CTRL-C again and it should be good to go.
4. You don't really need to clean up anything on sandbox, but if you'd like to you can do it with the Mephisto helper functions. The other ones have shut down completely, but `delete_hits.py` isn't telling you they are.

**Comment by kushalchawla** [comment]
Hey @JackUrb 

Thanks for the reply. I will explore Mephisto.

Further clarifications: 
3. So the right way to shut down is:

Once I press ctrl-c, no need to worry about the iterations of "Expiration of unassigned HITs". Instead, we need to look at the time specified in "assignment_duration_in_seconds", which is 30 minutes by default. So wait for 30 minutes after the first ctrl-c and then press another ctrl-c? Is this correct?

4. So it seems like: As a sandbox worker, if I am not able to see any task in the UI, then it has already been shut down correctly, regardless of whether delete_hits.py catches it or not? 

If this is the case, then probably waiting for just one iteration of "Expiration of unassigned HITs" (takes just a few seconds) is enough (rather than 30 mins) since that seems to remove the task from the sandbox UI. -> Hoping similar behavior in the live setting.

Thanks.

**Comment by kushalchawla** [comment]
Hey @JackUrb  

I think delete_hits.py works well for my use-case but if you could please clarify the above, I would be grateful.

Thanks,
Kushal.

**Comment by stephenroller** [comment]
Ah sorry, Jack went on holiday, hence his slow response.

- If you're in sandbox, you can Ctrl-C twice to skip the "Expiration of unassigned HITs" step. It's okay.
- If you're live, you should ctrl-c exactly once, and then wait for the system to safely shut down. It should take about 30 minutes. If you don't wait for a clean shutdown, you might get angry emails from turkers who couldn't load your task.

**Comment by kushalchawla** [comment]
Thanks a lot for a very lucid reply, @stephenroller. I will keep this in mind.
