### ISSUE TITLE
Blender: Quick Question about Persona

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2873]
Hello,

**Firstly, Is it possible to tell Blender about the "human's persona"?**
E.g, if we want the following:

Blender Persona: "I am a lawyer"
Human's Persona: "I am a doctor"

Is it possible to tell blender the human's persona, perhaps by having the human `act()` and return something like: "partner's persona: I am a doctor"?

Or is the only way to tell blender about the human's persona is to simply have the human just utter "I am a doctor"?

**Secondly, is it possible for a human agent or blender agent to have more than one turn in a row?**
E.g like:
```
Human: Hello
Human: How are you?
Blender: Good thanks
Human: That's nice
Blender: I know right
```
So that potentially the human could utter multiple persona's before beginning the conversation? E.g
```
Human: partner's persona: I am a doctor
Human: partner's persona: I went to medical school
Human: How are you today?
Blender: Good thanks, how about you?
...
```
Or is this the wrong approach to setting the human's persona?

Thanks for your time

**Comment by stephenroller** [comment]
We don’t currently support the model or the human going twice in a row, but you can emulate it by concatenating the multiple messages with a newline.

BlenderBot was not trained to see the partner’s persona, no.  You could re-fine tune it, but I don’t think it would work well, since in the original data collection, the humans were not aware of each other’s persona, and were instructed to get to know each other.

**Comment by Hilal-Urun** [comment]
Can we select the exactly one persona which is specified for blenderbot and every time we speak same persona ?
