### ISSUE TITLE
MTurk UI components flickering

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/ParlAI#2897]
Hi.

A couple of MTurkers report that their screen flickers, i.e., a few components disappear and appear continuously (like all the time). I spent hours trying to understand what the issue can be but no luck. In fact, I was unable to even reproduce the error at my end.

Most of the Turkers (including myself) did not face this issue.

Can it be something to do with my React code + browser settings? I am really not sure. I guess, if someone has already experienced this, please guide. One option is to just let it be, given it's rare.

Tagging my savior: @stephenroller @JackUrb

**Comment by JackUrb** [comment]
We've heard some reports of this as well with the baseline chat implementation, but generally this is caused by some instability in the react code with some older browsers. Our implementation here was pretty hacky (in that the frontend wasn't necessarily designed with rigorous react understanding), and as such certain state updates can cause weird things to happen regarding frame refreshing. If something you're doing is triggering the `onInputResize` or more generally `componentDidUpdate` of various components on every refresh, you'll end up with that kind of flicker.

Fortunately we have worked out a better frontend model in `Mephisto`, but in the meantime the above is the best advice I have.

**Comment by kushalchawla** [comment]
Hey @JackUrb 
Thanks a lot for your reply. I will verify this in the code and will probably update the instructions to use the latest browsers. As always, thanks a lot!

**Comment by kushalchawla** [comment]
@JackUrb Just to add here, one of the Turkers reported that Zooming in stopped the flickering for them. :) I have now updated my instructions to reflect this.
