### ISSUE TITLE
How to create Custom BlenderBOT model with parameters somewhat between 90M and 2.7B using parlai framework ?

### ISSUE THREAD

**Issue by aadityachapagain** [facebookresearch/ParlAI#2971]
Its been several weeks I am playing around with blender bot and parlai framework. **And I was wandering How can I create Blender bot but with parameter of around 1.5B  i.e between 90M and 2.7B model.**
<br />
Since 90M model is too small and 2.7B model is too big for me.
<br />
**Is there any way we could do this in parlai framework without needing to change much of the code.**

Thanks

**Comment by aslu98** [comment]
Hello,
I tried to do something similar by freezing part of the layers of the models, setting requires_grad to False for part of them. 
For example I used the 2.7B model and freezed 200 layers and I have around 1.8B parameters to train while the rest of them will stay the same. 
This is working for me as I could not train at all the full 2.7B model with my GPUs because of cuda out fo memory, but I am not done with the training yet so I don't know if the model will be good enough.
