### ISSUE TITLE
shared information between two human worker in one conversation

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/ParlAI#3030]
I'm developing a human-human chat collection task, which needs to present a shared message between two workers before the conversation. There are two problems I don't know how to solve:
1. In one chat task, two human workers need to share the same message before the conversation.
2. Shared messages are different across tasks.

I plan to present this message in MTurkOnboardWorld class. But, it looks like this class needs assignment_id to solve the above problems. I don't know where I can get assignment_id and pass it to MTurkOnboardWorld class.

Is there any way to solve these problems?

**Comment by stephenroller** [comment]
It's been a while since I tried, but in my experience when the world is created, you have an opportunity to initialize any shared state. You already have the list of agents, which can be two humans:

https://github.com/facebookresearch/ParlAI/blob/f2b1f6faba2c51f92d97f1ac4b848d7e920f5099/projects/controllable_dialogue/mturk/worlds.py#L260-L271

For instance in the Wizard evaluation task, we have the world track the conversation topic:

https://github.com/facebookresearch/ParlAI/blob/f2b1f6faba2c51f92d97f1ac4b848d7e920f5099/projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py#L199-L201

The topic itself was chosen in the onboard world:

https://github.com/facebookresearch/ParlAI/blob/f2b1f6faba2c51f92d97f1ac4b848d7e920f5099/projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py#L96-L101

**Comment by JackUrb** [comment]
I gave some insights for this in the Mephisto repo: https://github.com/facebookresearch/Mephisto/issues/236
