### ISSUE TITLE
Questions on agent selection

### ISSUE THREAD

**Issue by viperby** [facebookresearch/ParlAI#3136]
Hi, I'm training a model in other languages and have some preliminary results. I think I will submit it to the warehouse when the model is basically usable.

I like this framework very much. From the test situation, it brings me great surprise and shock. I am very grateful to the contributors for their hard work.

When I study this framework, I often have a puzzle. For example, what kind of agent should I refer to for training on tasks like Wikipedia? Which of the existing tasks is the most suitable agent for the current task?

I know it's ridiculous, but I hope that there will be a hint or suggestion for the existing task agent in the document or task list, which can give a preliminary reference to people like me who are eager to understand the framework but don't know how to start.

Looking forward to reply!

**Comment by stephenroller** [comment]
I'd recommend reading some of the research papers around these models and such. The ones from our group (see the README in the "projects" folder) can be a place to start.

We've tried to engineer ParlAI so that you can mix and match most datasets with most models. So the choice of data and agent is more like, "what are you looking to build, or what research question are you looking to answer?", rather than what is compatible with what.

**Comment by viperby** [comment]
@stephenroller 
Thank you for your reply. I think I understand. Maybe that's why it's so good.

I will try different possibilities to achieve the best results.

Thank you for your efforts
