### ISSUE TITLE
Transformer variants in Bi-encoder and Poly-encoder

### ISSUE THREAD

**Issue by huaxiadadi** [facebookresearch/ParlAI#3201]
Hi Kurt @klshuster , could you please tell me why you choose to use XLM architecture in Bi-encoder and Poly-encoder('--variant xlm' )?  Did you try the normal Bert architecture? Thanks a lot!

**Comment by stephenroller** [comment]
This was done because the originally pre-training was done with the XLM architecture. The XLM architecture in the retrieval models is the same as "pre-layer norm" discussions you see in the literature. It tends to be more stable to train in pre-training. Original "aiayn" architectures also work but tend to be harder to scale

**Comment by stephenroller** [comment]
https://openreview.net/forum?id=B1x8anVFPr here's a careful comparison you can see, though the pre-LN methodology predates this paper.

**Comment by huaxiadadi** [comment]
> This was done because the originally pre-training was done with the XLM architecture. The XLM architecture in the retrieval models is the same as "pre-layer norm" discussions you see in the literature. It tends to be more stable to train in pre-training. Original "aiayn" architectures also work but tend to be harder to scale

Gotcha, thank you very much!
