### ISSUE TITLE
Error in eval mode for the bAbI dll task

### ISSUE THREAD

**Issue by aleSuglia** [facebookresearch/ParlAI#332]
Hi there,

I'm trying to use the Dialogue Language Learning dataset through the `eval_model.py` script. It seems that the teacher always says that the answer is correct. This is an example session that I tried. 

First of all, I executed from the command line the script in this way specifying that the model should be a human:
```
python3 examples/eval_model.py -t dbll_babi:task:2_p0.5 -m local_human
```

An example of interaction with the teacher is reported in the following snippet:
```
[reward: 0.0]
[dbll_babi:task:2_p0.5]: Mary travelled to the garden.
Daniel went to the kitchen.
Where is Mary?
[cands: kitchen|bedroom|garden|office|bathroom|hallway]
Enter Your Message: office
---
{'total': 1, 'accuracy': 0, 'f1': 0, 'hits@k': {1: 0, 5: 0, 10: 0, 50: 0, 100: 0}}
[reward: 1.0]
[dbll_babi:task:2_p0.5]: Correct!
Sandra went back to the bathroom.
Sandra moved to the garden.
Where is Sandra?
[cands: kitchen|bedroom|garden|office|bathroom|hallway]
Enter Your Message: bathroom
---
{'total': 2, 'accuracy': 0, 'f1': 0, 'hits@k': {1: 0, 5: 0, 10: 0, 50: 0, 100: 0}}
[reward: 1.0]
[dbll_babi:task:2_p0.5]: That's correct.
John travelled to the office.
Mary journeyed to the kitchen.
Where is Daniel?
[cands: kitchen|bedroom|garden|office|bathroom|hallway]
``` 

As you can see, I've intentionally inserted the wrong answers but the reward that the teacher gives to me is always 1 and it says that my answer is correct.

Am I doing something wrong or is there a bug in the code?

Thank you in advance for your answer!

**Comment by alexholdenmiller** [comment]
Thanks for flagging, we'll take a look!

**Comment by klshuster** [comment]
Hi,

The Dialogue Language Learning dataset (dbll_babi) is used as a supervised learning task, so the dialog history is assumed to be the true history. That is, the agent is trained via observing interactions between a teacher and student - in the task 2 evaluation dataset, all the responses that the student provides are correct, so the teacher is responding accordingly. 

The feedback you are seeing is the feedback in the dataset, not necessarily the result of what you have entered as an answer (notice that accuracy reflects, appropriately, that you have provided an incorrect answer). It is important for the agent to see the feedback, as otherwise the model would be seeing a story presented in a different format from which it was trained.

Hope that helps!
