### ISSUE TITLE
Slow GPU performance

### ISSUE THREAD

**Issue by khomchyk** [facebookresearch/ParlAI#3465]
Hello!
Would you be so kind to help me to understand the issue with running ParlAI model on the GPU.
It seems that to run the model on the CPU-based machine is much faster than on the GPU one.

Config of the CPU machine:
 - MacBook Pro 2020 (2.3GHz Intel Core i9 processor, 32 GB memory)

Config of the GPU machine:
 - Azure Standard NC6 (6 vcpus - 56 GB memory, ubuntu 18.04, Nvidia Tesla K80 - 12 GB)
 
nvidia-smi info from the Azure machine:
![2021-02-23 16 05 03](https://user-images.githubusercontent.com/2414058/108863034-15e79a00-75f1-11eb-8592-84e06be1687c.jpg)

Model config:
    
```
       model_config = {
    	    'model': 'local_human',
    	    'model_file': 'zoo:blender/blender_90M/model'
        }
```
   
CPU profiling:
<img width="1224" alt="Screenshot 2021-02-23 at 16 09 59" src="https://user-images.githubusercontent.com/2414058/108863708-c6ee3480-75f1-11eb-92d9-04772ac2381f.png">

GPU profiling:
<img width="1229" alt="Screenshot 2021-02-23 at 16 09 48" src="https://user-images.githubusercontent.com/2414058/108863821-e5543000-75f1-11eb-9a6c-8047ba9ecbaa.png">

It seems that running on Azure-GPU is almost 3x times slower.
Especially the method ~:0(<method 'bmm' of 'torch._C._TensorBase' objects>) is much slower on GPU.

I attached the profiling files:

[profiling.zip](https://github.com/facebookresearch/ParlAI/files/6029801/profiling.zip)
To run and see results:
```
snakeviz cpu.prof
snakeviz gpu.prof
```

Could you, please, advice what could be wrong with running on the GPU or maybe is something incorrect with my model's config?

**Comment by stephenroller** [comment]
A few things:
- That model involves a lot of cpu/gpu transfer in the implementation of beam blocking, which slows it down.
- That model is very small, which means the computation is dominated by transfer.
- We probably have a regression in TorchGeneratorAgent to boot
- I'd be much more interested in an apples-to-apples comparison of the CPU on that Azure VM.

Mitigations:
- You'll see a much larger difference in a larger model, like BlenderBot 2.7B or 1B
- That model is probably using fp16, but you're using a very old GPU on which fp16 will actually be slower. Try using --fp16 false (for both)
- You're paying for this high GPU <-> CPU overhead but using a single batch. Increasing batchsize will dramatically increase throughput. Doubly so if you can use dynamic batching.
- Make sure you're installing torch with conda so that you're getting a nice optimized build for your machine.

**Comment by khomchyk** [comment]
@stephenroller Stephen, thanks for a quick and detailed answer!
It really helped to understand the bottlenecks.

I tried to do more experiments with my current Azure setup.
With CUDA, without fp-16, blender_90M:

    #1 time: 0.7303366661071777
    #2 time: 0.6700782775878906
    #3 time: 0.6654324531555176
    ...
    #15 time: 0.6854743957519531
    Total time:  10.117816686630249

With CUDA, with fp-16, blender_90M:

    #1 time: 1.5443954467773438
    #2 time: 1.388392686843872
    #3 time: 1.3896188735961914
    ...
    #15 time: 1.387455940246582
    Total time:  21.01096749305725

Without CUDA(only CPU), blender_90M:

    #1 time: 1.2738816738128662
    #2 time: 1.0603864192962646
    #3 time: 1.0774791240692139
    ...
    #15 time: 1.0592575073242188
    Total time:  16.491455793380737

With CUDA, blender_3B:

    #1 time: 10.191441774368286
    #2 time: 10.227393627166748
    #3 time: 10.203410148620605
    ...
    #15 time: 10.220684289932251
    Total time:  153.27050757408142
    
 Without CUDA, blender_3B:

    #1 time: 13.495542287826538
    #2 time: 13.51427435874939
    #3 time: 13.535935878753662
    ...
    #15 time: 13.675921440124512
    Total time:  204.11873936653137
    
So I would like to add some insights:
- GPU is faster than CPU :)
- using of fp-16 is decreasing the performance


Also, I tried to run some distilled blender model, but get the following error:

    Traceback (most recent call last):
    File "perf.py", line 25, in <module>
    process('who is steve jobs')
    File "perf.py", line 18, in process
    response = model.act()
    File "/venv/nlp/lib/python3.7/site-packages/parlai/core/torch_agent.py", line 1951, in act
    self.self_observe(response)
    File "/venv/nlp/lib/python3.7/site-packages/parlai/core/torch_agent.py", line 1752, in self_observe
    last_reply = self_message['text']
    KeyError: 'text'

Code:

    from parlai.core.agents import create_agent
    model_config = {
	    'model': 'local_human',
	    'model_file': 'zoo:blender/blender_400Mdistill/model',
    }
    model = create_agent(model_config)
  
    def process(text):
	    model.observe({
		    'episode_done': False,
		    'text': text,
		    'payload': None,
	    })
    
	    response = model.act()
	    return response['text']
    
    model.history.reset()
    process('who is steve jobs')
   
Could you, please, help me to understand what is causing this error?
(at the same time everything is OK with regular, not distilled models)

**Comment by stephenroller** [comment]
FP16 is expected be slower on any NVIDIA hardware that doesn't have tensor cores. This is because the GPU does the calculation in fp32 then converts to fp16, instead of natively doing it in FP16. Volta cards (like a 2080 or a V100) should see a ~2.5x speedup. If you can afford lower latency for throughput, FP16 can give you a win on older cards too by allowing you to increase the batchsize.

W.rt. distilled, try adding the option `"skip_generation": False`. Looks like the option file we distribute with that model wasn't set.

**Comment by stephenroller** [comment]
Here's some runs on a V100 I have access to

model | fp16 | fp32 | cpu
------ | ---- | ---- | -----
90M | 0.772 |  0.838s | 2.027s
400M | 0.787 | 0.831s | 10.678s
3B | 1.492 | 1.544s | 92.711s 

In the first two, I'm probably bottlenecked by transfer to the GPU more than anything, probably mostly because of beam blocking. In all, I'm not seeing much benefit from fp16, which is probably because there's not enough computation to saturate the machine (small batchsize).

Here's my benchmark script:
```python
import timeit
import argparse
from parlai.core.agents import create_agent_from_model_file

TRIALS = 10
TEXT = 'Who is Steve Jobs?'

MODELS = {
    'dis': 'zoo:blender/blender_400Mdistill/model',
    '3b': 'zoo:blender/blender_3B/model',
    '90': 'zoo:blender/blender_90M/model',
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', choices=MODELS.keys(), required=True)
    parser.add_argument('-n', '--trials', default=TRIALS)
    parser.add_argument('--no-cuda', action='store_true')
    parser.add_argument('--no-fp16', action='store_true')
    args = parser.parse_args()

    mf = MODELS[args.model]
    trials = args.trials

    agent = create_agent_from_model_file(
        mf,
        {
            'model_parallel': False,
            'interactive_mode': True,  # turns on generation and saves memory
            'no_cuda': args.no_cuda,
            'fp16': not args.no_fp16,
        },
    )

    total = 0.0
    for _ in range(trials):
        start = timeit.default_timer()
        clone = agent.clone()
        clone.observe({'episode_done': False, 'text': TEXT})
        response = clone.act()
        print(response['text'])
        end = timeit.default_timer()
        total += end - start
    print(f"Average: {total/trials:.3f}")


if __name__ == '__main__':
    main()
```

**Comment by khomchyk** [comment]
@stephenroller Stephen, thanks a lot for your efforts, explanations and running the benchmarks!
It gives a good overview what response time could be with different models. 

Also, about distilled model - adding `"skip_generation": False` helped and everything is working now.

I think that the issue could be closed.
