### ISSUE TITLE
Search_Server Argument with BlenderBot 2.0

### ISSUE THREAD

**Issue by InquestGeronimo** [facebookresearch/ParlAI#3816]
Hi, is it possible to share an example URL for the "search_server" argument that is required to run BlenderBot 2.0? I tried 'https://www.google.com/search?q=' and other variants but with no success. Not sure if I'm writing it correctly.

Thank You

**Comment by mojtaba-komeili** [comment]
Hi, you need to setup your own search server. Models consider it to be an external module and completely independent. Checkout `_query_search_server` and `_retrieve_single` methods in [SearchEngineRetriever](https://github.com/facebookresearch/ParlAI/blob/09f5508cf20fc47d109c863f4ca517b4597934c0/parlai/agents/rag/retrieve_api.py#L73) for designing your search server API.

**Comment by JulesGM** [comment]
that's too bad, that means people will have to work hours (multiple) to get this to work.
All of this is still awesome ofc.

**Comment by JulesGM** [comment]
I coded one. Right now uses `googlesearch`, but easy to modify to use another search engine.
https://github.com/JulesGM/ParlAI_SearchEngine

**Comment by JulesGM** [comment]
I created one @InquestGeronimo @mojtaba-komeili  https://github.com/JulesGM/ParlAI_SearchEngine

**Comment by InquestGeronimo** [comment]
Thank you @JulesGM , looks great.

**Comment by wjeliot** [comment]
Here's a search server implemented in Node.js: https://github.com/wjeliot/parlai-search_server-node. Like the solution from @JulesGM, it uses an html-to-text library to scrape pages, although this method returns quite low quality data and could use some refining in order to support the model better.

Also, here's a Google Colab with Blender Bot 2.0 inside: https://colab.research.google.com/drive/1qYe0-gHgPQTLXCuZZuT6W9fAU-AiIX0j?usp=sharing. It will likely crash using the standard runtime, so make sure to select a high-RAM runtime. When the model eventually loads, it works... but the predictions take a very long time to make.

**Comment by JulesGM** [comment]
Also added a notebook that works in large memory instances https://github.com/JulesGM/ParlAI_SearchEngine/blob/master/colab_large_mem.ipynb

**Comment by JulesGM** [comment]
Actually my script has worked for some people on regular Colab instances, so you may still want to try.

**Comment by Jawad1347** [comment]
> Actually my script has worked for some people on regular Colab instances, so you may still want to try.

your script has worked for me in local machine as well.
