### ISSUE TITLE
Documentation on Finetuning Blenderbot 2.0 on your own dataset

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/ParlAI#4014]
**Is your feature request related to a problem? Please describe.**
I would like to finetune the blenderbot 2.0 with domain-specific data.  For blenderbot 1.0, there is a script that explains the fine-tuning.  

**Describe the solution you'd like**
A script that shows the fine-tuning procedure.

**Comment by klshuster** [comment]
The [model card](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md) provides the necessary hyperparameters for training; see #3940 for an example invocation

**Comment by DrMatters** [comment]
> The [model card](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md) provides the necessary hyperparameters for training; see #3940 for an example invocation

Hello! Seems like the model card you mentioned doesn't provide information about a large number of datasets used for training. There are like 7 datasets according to the parameter "multitask_weights" but only [4 are mentioned](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md#datasets-used).

**Comment by stephenroller** [comment]
> Hello! Seems like the model card you mentioned doesn't provide information about a large number of datasets used for training. There are like 7 datasets according to the parameter "multitask_weights" but only [4 are mentioned](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md#datasets-used).

The BST task are listed as one, but are actually 4 tasks: ConvAI2, Empathetic Dialogues, Wizard of Wikipedia, and Blended Skill Talk. Add in WoI, MSC and BAD and you get 7.

**Comment by DrMatters** [comment]
@stephenroller, Hello! Thank you for helping.
Why didn't you save the task data in the model.opt as was done in blenderbot 1?

**Comment by klshuster** [comment]
The model was trained on some tasks before they were released publicly (woi, msc), and several flags/names changed in the open-source process, so we did not have a change to convert all of the `.opt` parameters

**Comment by Joaoluislins** [comment]
Hello @klshuster! :)

Most of the example scripts here to finetune bb2_3b uses truncate = 128, as bb1_3b, the used init-model has this specifity.
I would like to try finetuning bb2_3b with truncate = 1024...But i'm with some questions about this procedure:

- Can I use the summsc_fidrag3B or msc3B_1024 as the init model? as they already have truncate 1024?

- Or should I use blender3B_1024 inserting more epochs in order to train its not learnt positional embeddings? (in this case, would learn-positional-embeddings be True?)

- Or even, should I first train blender_3B on a projects.msc.agents.memory_agent:MemoryLongFidAgent as described in #4035 to train the positional embeddings and then train again this model with the blendebot2 fid agent?

Thankss
