### ISSUE TITLE
Questions about the truncate flags for finetuning BlenderBot2_3B

### ISSUE THREAD

**Issue by sjscotti** [facebookresearch/ParlAI#4035]
Hi!
I see in the model card for BlenderBot2 `ParlAI/parlai/zoo/blenderbot2/model_card.md` (it says 2.7B, I am assuming it is the same for 3B).  That the parameters `truncate` , `text_truncate` ,  `label_truncate` are all set to `128`.  However, I have a dataset that I want to use to finetune the model that has text strings in the conversations that are larger, but less than 512 characters.  So in finetuning the model, I want to change these parameters to `512`.  When I did that (for just `label_truncate` I believe, the other 2 parameters did not cause an error message), I got the error message `You are inputting a sequence of 135 length, but only have --n-positions 128. Set --truncate or increase --n-positions`.  So I am unsure of the best path forward.  Can I just increase `n-positions`?  Is changing any of these truncate parameters from the original model values allowed?  Any advise would be appreciated.
Thanks!

**Comment by klshuster** [comment]
Hi there, you're getting this error because the base model for BB2 (3B) only has 128 position encodings. There are two ways you can remedy this:

1) You can try using BB2 400M, which can support 512 positions (you would then specify `--n-positions 512`)
2) The MSC project provides an implementation that allows you to add additional position encodings beyond the 128; you would want to specify the following:

`--model projects.msc.agents.memory_agent:MemoryLongFidAgent --n-init-positions 128 --n-positions 1024 --init-model zoo:msc/blender3B_1024/model --dict-file zoo:msc/blender3B_1024/model.dict`

**Comment by sjscotti** [comment]
Thanks!  I am starting with BB2 400M and in the midst of finetuning it with my corpus plus Blended_Skill_Talk (to prevent over training that would result if I used just my corpus).  It will take a few more days to finish the fine tuning there (I am using a single GPU with only 8GB of GPU memory) and see what results.  I may go to BB2 3B using your suggestion if I don't get good results with BB2 400M.
