### ISSUE TITLE
seq2seq with Pytorch cause GPU out of memory

### ISSUE THREAD

**Issue by ZixuanLiang** [facebookresearch/ParlAI#407]
Hello, when I train the example seq2seq model on ubuntu dataset on Parlai, GPU is out of memory after training on a few thousand of examples. Is it related to Pytorch? I am not sure how this happens.

**Comment by alexholdenmiller** [comment]
Hi Zixuan, what are the parameters you're using? You could paste the exact command you used to launch. Thanks!

**Comment by ZixuanLiang** [comment]
@alexholdenmiller The command I used was: python train_model.py -m seq2seq -t ubuntu -bs 8 -e 1 -mf /tmp/model_s2s

**Comment by ymihay** [comment]
@alexholdenmiller I'm facing the same issue. The memory used by process is increasing until until it's killed by system process. It's killed when on 60 GB. Was it designed to consume much more memory?

**Comment by alexholdenmiller** [comment]
This is definitely not expected and I hadn't run into that myself (had trained out open subtitles for days without hitting that in the past)--I'll continue to investigate and patch as soon as I identify the issue.

**Comment by alexholdenmiller** [comment]
@ZixuanLiang for running out of CUDA memory, I believe the issue here is just that some of the ubuntu examples can have particularly long sequences, so at a random point you hit a batch that gets too big to fit in the GPU memory any more. You can mitigate this by setting the `--truncate` flag for the seq2seq model, e.g. `-tr 48` to only keep the last 48 tokens. This will both speed it up and help to prevent this issue. After increasing with some random variation for a while, the GPU memory usage should flatten out and remain constant for the rest of training (esp after 1 epoch it should never increase again).

I'm surprised it's happening so clearly with this dataset. It's possible there's a bug somewhere else in the seq2seq code using too much CUDA memory, but I'm not aware of it at the moment. Let me know if using the `tr` flag doesn't remedy this for you.

@ymihay in your case, you're referring to the system RAM not the GPU memory, I'm guessing. We recently added a feature which dramatically speeds up training at the cost of significantly more RAM. This can be disabled using `--batch-sort false` or mitigated using `--context-length {small integer}`. I'm adding a warning now to print this if RAM is used up from this approach.

**Comment by alexholdenmiller** [comment]
closing now but feel free to reopen if you have any further questions.
