### ISSUE TITLE
Blenderbot: Skip turn during conversation

### ISSUE THREAD

**Issue by mailong25** [facebookresearch/ParlAI#4076]
Current Blenderbot 2.0 required users to respond at their speaking turns in order to proceed with the conversations.
This could be an issue if the users prefer to stay silent or they simply don't know what to say.
.
**Is there a way to skip a turn?** 
I tried to use noncommittal responses, such as uh-huh, I see, oh, yeah, as a representative for the silence but it not working well for all cases.
.
To clarify the question, here is an example of how I think the chatbot should behave:
```
User: I study computer science
Bot:   That's cool. Do you have a job lined up after you graduate?​
User: honestly, I don't know what might happen next​
Bot:   I hope you find something soon. I know how hard it is to find a job these days.​
User: [Silence/Skip Turn]
Bot:   However, it's not a problem if you are competent enough. Which do you like most about your major?
```

**Comment by klshuster** [comment]
all of these methods work by setting the probability of offending tokens to be zero, so that the model is forced to *not* choose them. 

blocking n-grams happens [here](https://github.com/facebookresearch/ParlAI/blob/92e4fca96b83a2d2eecd815efcd6d784d885adbb/parlai/core/torch_generator_agent.py#L1351-L1374)

beam min length blocks the end of sentence token [here](https://github.com/facebookresearch/ParlAI/blob/92e4fca96b83a2d2eecd815efcd6d784d885adbb/parlai/core/torch_generator_agent.py#L1394-L1397)

etc.
