### ISSUE TITLE
blenderbotSmall context format

### ISSUE THREAD

**Issue by Lkh97** [facebookresearch/ParlAI#4109]
Hi there, 

I need to know about the way the context is formatted for the training of <b>blenderbotSmall</b>. For instance, when you want to incorporate knowledge or persona plus the n past utterances as the context how they are formatted and what special tokens are used. 

For instance:  \<bop\> persona1 \<eop\> \<bop\> persona2 \<eop\> \<bok\> knowledge1 \<eok\> \<s\> utterance1 \</s\> \<s\> utterance2 \</s\> and imagine,
bop: means the begining of the persona,  
eop: means the end of persona,
bok: means the begining of the first knowledge chunk, 
eok: means the end of the first knowledge chunk, 
and so on. I mean this is what I am looking for to see what context format you employed to feed in the data and train the <b>blenderbotSmall</b>. 
I have not been able to find that in your repository. I appreciate your help and guidance on how this is done. 

Thanks  🙏🏻

**Comment by yana-xuyan** [comment]
Thank you so much for your reply! I tried to reproduce the blenderbotsmall model with the command line given on the project page (https://parl.ai/projects/recipes/). I checked the content when running the code by printing the content of `history.get_history_vec()`, which is here (https://github.com/facebookresearch/ParlAI/blob/1bf1c8152e6326a63afb3c587a62c69330731f80/parlai/core/torch_agent.py#L1468). It seems like the dialogue history and the corresponding persona/knowledge sentence are make in the following way:

"new york city __newln__ i really love new york city for many reasons. __newln__ is it the beautiful skyline or because the city never sleeps"

Could you please tell me whether this is the way when pretraining the released BST 90M model?

**Comment by klshuster** [comment]
yes this looks akin to what was used with the BST90M model

**Comment by yana-xuyan** [comment]
Thank you very much for your reply!
