### ISSUE TITLE
List of possible arguments for methods (create_agent_from_model_file, observe, act)

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4504]
Hello

I'm using the following commands in Python:

```
from parlai.core.agents import create_agent_from_model_file
opt = {'skip_generation': False}
blender_agent = create_agent_from_model_file("zoo:blender/blender_1Bdistill/model", opt)
....
blender_agent.observe({'text': userText, 'episode_done': False})
response = blender_agent.act()
```

Is there a list and explanations of the possible arguments and options for create_agent_from_model_file, observe, and act? I also don't understand what skip_generation and episode_done is doing.

**Comment by Eichhof** [comment]
Does somebody has an idea?

**Comment by AbreuY** [comment]
> Does somebody have an idea?
Hi, maybe these parameters can help you.

```
 otp= {
    "model_file": "zoo:blender/blender_90M/model",
    "model": "transformer/generator",
    "beam_min_length": 20,
    "batchsize": 1,
    "skip_generation": False,
    "interactive_mode": False,
    "beam_size": 10,
    "inference": "beam",
    "beam_block_ngram": 3,
    "beam_context_block_ngram": 3
}
```

In the project where I'm working I only use this config.

```
opt = {
    "model_file": "zoo:blender/blender_90M/model",
    "model": "transformer/generator",
    "interactive_mode": True
  }
```

Were you able to handle cloning an agent via a user ID to maintain a different context? I am asking this because I am in a similar situation but I am stuck on this part. And I have seen that you have commented on something similar.
