### ISSUE TITLE
Table 2 in paper *Internet-Augmented Dialogue Generation*

### ISSUE THREAD

**Issue by joemzhao** [facebookresearch/ParlAI#4854]
Dear authors,

thanks for the great work! I was trying to reproduce the result 10.6 in Table2 cell: WizIntValidation-PPL, Transformer (gold knowledge), BART-Large 400M of the *Internet-Augmented Dialogue Generation* paper (https://arxiv.org/pdf/2107.07566.pdf).

I can get the result (17.4 PPL) without knowledge using (as in https://parl.ai/projects/sea/):

``parlai eval_model -mf zoo:sea/bart_base/model -t wizard_of_internet -dt valid -bs 4 ``

But adding the gold knowledge sentences:

``parlai eval_model -mf zoo:sea/bart_base/model -t wizard_of_internet -dt valid -bs 4 --prepend-gold-knowledge True ``

gives 13.22 PPL. Do I need to specify more options to get 10.6 PPL? Thank you very much!

My environment: cuda:11.2.0, cudnn8, parlai:1.7.1, python:3.8.3, pytorch:1.12.1. gpu: quadro RTX 8000

**Comment by mojtaba-komeili** [comment]
We are glad to see your interest in the paper. The `bart_base` model that you are using here is not trained with seeing the gold knowledge. The one in the table you reference was fine-tuned with gold knowledge in its context. That's why it can utilize that knowledge better and go to such low PPL. We did not publish the model that was fine-tuned with gold knowledge. But you can easily train one with the options you used here for validation. The results may not be exactly the same because of the randomness and hyper-parameter differences, but I expect it to get really close.

**Comment by joemzhao** [comment]
Thank you Mojtab for the prompt reply! Yes I also realize the ckpt I use was not the one finetuned with gold knowlege.
Still, I think it shows the strength of adding knowlege (17.4 -> 13.22), as the paper discussed.
I will finetune a model on the gold knowledge. Thanks for the reply!
