### ISSUE TITLE
r2c2_bb3_agent

### ISSUE THREAD

**Issue by Dev-hestabit** [facebookresearch/ParlAI#4943]
I want to optimize bb3 so want to reduce 13 module that are using in r2c2_bb3_agent.py but how can we remove module. can anyone suggest some solution.

**Comment by kobzaond** [comment]
Hello, I have a question regarding the modules - are they run in parallel or sequentially? (e.g. search-decision and memory decision can be run in parallel, I guess).

**Comment by mojtaba-komeili** [comment]
Figure 2 in our [paper](https://arxiv.org/pdf/2208.03188.pdf) shows the details of dependency between various modules. Our intentions were mostly around the quality of the model responses and the science behind it, rather than the best performance in terms of throughput and the turn around time. One can refactor the code for better async implementation; this was not something that we aimed for.
