### ISSUE TITLE
Versioning ParlAI Package

### ISSUE THREAD

**Issue by deshraj** [facebookresearch/ParlAI#551]
ParlAI should have versioning so that it would become easy for anyone who is planning to use ParlAI as a dependency. Otherwise things will start break as the ParlAI codebase grows. 

To get started, first of all we need to select a versioning scheme to follow, see this link: https://packaging.python.org/tutorials/distributing-packages/#id59

**Comment by deshraj** [comment]
Also, it seems like ParlAI is not on Pypi. Is that intentional?

**Comment by jsedoc** [comment]
I second this. Do you have milestones and stable release timelines?

**Comment by alexholdenmiller** [comment]
re: pypi, currently intentional, as we are using ParlAI as an environment (download, install, do all work within that directory) rather than a dependency, as well as making a pretty frequent breaking changes / fixes.

Related to that, we do not have milestones / stable release timelines, as our milestones are not ParlAI features but rather research papers / projects, with updates to ParlAI coming up via Issues and PRs and anything we find we need for our research.

If we have a little more time soon, we may update the repository with versioning. If there are specific things we are breaking, please flag those for me--it will help to raise the priority of a versioning system and we can possibly mitigate breaks until such a system is in place.

**Comment by deshraj** [comment]
Thanks @alexholdenmiller for the reply. All of this sounds like a plan. Please feel free to close this issue for now.
