### ISSUE TITLE
Question about Facebook Dialog format.

### ISSUE THREAD

**Issue by Jackberg** [facebookresearch/ParlAI#619]
I think this format is not making full use of the data? Look at this example:
```
1 Hi how's it going?<TAB>It's going great. What's new?
2 Well I'm working on a new project at work.<TAB>Oh me too!
3 Oh cool!<TAB>Tell me about yours.
```
So the sentences appear as labels will never appear as queries unless coincidences, right? But actually the dialogue can be organised like this to make the best use of data, for this example:
```
1 Hi how's it going?<TAB>It's going great. What's new?
2 It's going great. What's new?<TAB>Well I'm working on a new project at work.
3 Well I'm working on a new project at work.<TAB>Oh me too!
4 Oh me too!<TAB>Oh cool!
5 Oh cool!<TAB>Tell me about yours.
```
Is there any functionality to enable this? Or maybe the agents are using dialogue data like this, in case I didn't understand it correctly.

**Comment by jaseweston** [comment]
Well, ... you can use the data how you like, making your agent play both roles.
Or, more simply, you can have the data duplicated -- two dialogues which are the same -- but person1 (lhs) and person2 (rhs) have the roles switch.
But.. you wouldn't want to do what you did, because it breaks the actual meaning of the dialogue flow (who is person1, who is person2).

**Comment by Jackberg** [comment]
Yeah you're right @jaseweston . I confused the dialogues with Q-A pairs. For the example I gave, I think it's acceptable to use each sentence both as Query and as Answer. But for dialogues, it's important to obey the actual flow. I'll close this issue.
