### ISSUE TITLE
Pytorch Installation failed with requirements_ext.txt

### ISSUE THREAD

**Issue by chetkhatri** [facebookresearch/ParlAI#66]
My review points are as below:
1. We must provide installation steps at README.md
2. provided requirements_ext.txt installation with pip always fails because only saying pytorch fails and exception as below:

  ```
Failed building wheel for pytorch
  Running setup.py clean for pytorch
  Running setup.py bdist_wheel for regex ... done
  Stored in directory: /home/chetan/.cache/pip/wheels/22/bd/1e/4fb7e5438c893f68d145c1748e29dafe5d215bad5dedef8037
Successfully built regex
Failed to build pytorch
Installing collected packages: pytorch, regex
  Running setup.py install for pytorch ... error
    Complete output from command /home/chetan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XTOHDh/pytorch/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o2gbGm-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XTOHDh/pytorch/setup.py", line 13, in <module>
        raise Exception(message)
    Exception: You should install pytorch from http://pytorch.org
    Created new window in existing browser session.
```
It looks we can probably append this to requirements.txt only or else use saumith's pip command as given at pytorch.org
3. What is need of setup.sh if setup.py would be used as per installation steps at README.md

**Comment by alexholdenmiller** [comment]
Thanks for the feedback @chetkhatri, I modified the readme installation instructions to be more specific, removed the requirements_ext.txt file and added specific instructions to the readme to install pytorch from their website. #74

I'll leave the setup.sh file--it basically just runs the command that the readme says to run. However, in some environments it can fail to install due to aliasing of `python` in a multi-install environment, so I'm not recommending using it on the readme.
