### ISSUE TITLE
Make `observations` in `batch_act` represent a single episode

### ISSUE THREAD

**Issue by hengyicai** [facebookresearch/ParlAI#753]
Due to some requirements of the model, a complete episode(or batch episodes) needs to be observed by the model in each training step(i.e., function `batch_act` or `act` in the agent class). Say the dialogue data is:
```
        1 X1    Y1
        2 X2    Y2
        3 X3    Y3
        1 X4    Y4
        2 X5    Y5
        3 X6    Y6
```
The model needs to receive the `observations` in `batch_act` like this:
```
{'text': x1, 'labels': [y1], 'episode_done': False}
{'text': x2, 'labels': [y2], 'episode_done': False}
{'text': x3, 'labels': [y3], 'episode_done': True}
{'text': x4, 'labels': [y4], 'episode_done': False}
{'text': x5, 'labels': [y5], 'episode_done': False}
{'text': x6, 'labels': [y6], 'episode_done': True}
```

Does ParlAI provide such a mechanism? If not, what should I do to achieve this goal? 
For now, I'm trying to implement a `BatchEpisodeWorld` class(counterpart to `BatchWorld` class) in `parlai/core/worlds.py`.

**Comment by alexholdenmiller** [comment]
No, "rows" in batches are explicitly unrelated in the current batchworld.

There are a few alternatives:
1) the batch-sorting functionality will give you examples in the following format:
```
{ text: x1, labels: [y1], episode_done: True }
{ text: x1y1x2, labels: [y2], episode_done: True}
{ text: x1y1x2y2x3 labels: [y3], episode_done: True}
```
that is, flattening the examples into their own episodes with their own separate context by combining the previous xs and ys with newlines. we are working on a better way to define how you want the examples to be flattened than just "join on newlines", but not this week.

2) store examples in an internal datastructure until the full episode has been seen, and then do a training step. the language model does something like this, because it trains on a fixed number of tokens with every update.

3) implement a new batchworld which does this. it's not great for the general case (what happens if an episode is longer than the batch size?) and the current system allows each row to have independent state associated (there's a shared instance of both the agent and the teacher associated with that row), but it could be hackable for this one experiment.

**Comment by hengyicai** [comment]
Thank you very much for your detailed reply! The solution 2 seems to work, which is also flexible for the agent. Thank you!
