### ISSUE TITLE
Command to train Persona-Chat baseline seq2seq model

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#834]
After looking at the [personachat](https://github.com/facebookresearch/ParlAI/tree/master/projects/personachat) directory. I was wondering what command to use to train the seq2seq model using ParlAI. It looks like there's a different seq2seq model being used. And some colleagues mentioned they tried to train with the default parlai seq2seq using the options from the paper and ran into out of memory errors until they reduced the batch size.

The question is, what command would you recommend using to replicate the baseline
eg: `python examples/train_model.py -t babi:task10k:1 -m seq2seq -mf /tmp/model_s2s -bs 32 -vtim 30 -vcut 0.95` 

Apologies that this sounds like such a lazy question and if there's an answer already that I missed but hopefully this will be of interest to other people as well.

**Comment by alexholdenmiller** [comment]
No problem, @Henry-E!

That's true that the projects/personachat/persona_seq2seq agent is a custom one (a modified version of an older seq2seq model) which uses task-specific code, e.g. parses out the persona separately and only remembers the last utterance in the dialog.

The general model in parlai/agents/seq2seq can be trained on the personachat data as well (but was not for the paper). We made a new version of the personachat dataset with some different preprocessing for the ConvAI2 competition (convai.io), which is marked as the `convai2` task in parlai. You can train the seq2seq model on this using `projects/convai2/baselines/seq2seq/train.py`.

We reduced the default batchsize in the file, but you can always do -bs N to lower it further. All the non-default hyperparams are set in that file (but the commandline overrides those if you want to try any changes).

**Comment by alexholdenmiller** [comment]
Note that the biggest difference for this seq2seq model is that it has no persona-specific code--it just treats the persona as past context, which it encodes using the encoder and does attention over.

**Comment by Henry-E** [comment]
Great, that's training perfectly. Thanks very much.

**Comment by Henry-E** [comment]
So I have a related question @alexholdenmiller about the baseline results. After training for a little bit the performance bottomed out at around 41 perplexity on the validation set. This is more or less in-line with the seq2seq results report in the paper of 40.53. In convai leaderboard though, the best perplexity for the seq2seq baseline is listed 31.35. Which is quite a bit better. Do you think there's something missing from the implementation or was it an unlucky run?

**Comment by Henry-E** [comment]
There's also a research oriented question that I've been curious about. Is there a large difference in performance between giving the personas their own separate encoder vs. encoding personas and last utterance in same encoder? The simplicity of throwing everything into the one encoder and separating different pieces using special tokens has a strong appeal. However I haven't been able to test what practical limits are for encoding length. Presumably both bidirectional rnns and attention manage to offset much of the information loss that occurs but I'm curious what your experience has been.

**Comment by jaseweston** [comment]
we're not sure... hopefully the competition will explore these issues!

**Comment by alexholdenmiller** [comment]
Let me run through those:
1) oom on validation: that's because training was hovering just below your limit and the validation may have had a slightly longer example than any in the training set which pushed it past the max. so this is normal, and may just need smaller batch sizes or some truncation of the inputs.
2a) that seems too high for bottoming out--my runs very consistently gets a lot lower than that (~31-34) is approx two hours when I trained with bsz 128. how long did that take? you may be training slower than on my GPU (esp with the lower bsz), so may need to e.g. double the validation time so it doesn't run out of patience as quickly, or may need to adjust the learning rate with that different bsz.
2b) however, note that this ppl you're seeing is based on the model's cross entropy loss. this means that it includes things like predicting the `__END__` token. the leaderboard is based on the separate eval_ppl script which does a much more careful job of evaluating and doesn't include these extra special characters from the model, so that the different models can be compared exactly. this ppl tends to be worse (e.g. adding a few points to the valid ppl, I mean of course predicting __END__ is easy!).
3) the seq2seq model in the personachat paper vs the seq2seq model you ran is quite different, and we trained them a little bit differently as well. most notably, I believe they only trained the persona_seq2seq model on one side of the conversation (e.g if A and B are talking, only train to predict B's responses from A, not A's from B); the convai2 task includes the conversations from both perspectives, effectively increasing the size of the training set. again though, the models are doing different things, and the seq2seq model you trained has a bunch of extra bells and whistles which can be helpful. for example, even just doing "post" attention vs the "pre" attention the persona-seq2seq model does I found to drop the ppl by a few points.
4) would love to see results on separated vs token-marked encoding of the persona!

**Comment by Henry-E** [comment]
Thanks so much for the response. That's super helpful. I'll try running more models with different options and see what I can figure out. 

The reason I mentioned using a separate encoder vs. token marked encoding was that was the main difference you noted between the personachat specific seq2seq and the main parlai seq2seq. As you said though, there's more features in the main parlai seq2seq so it's probably not a proper comparison.
