### ISSUE TITLE
Sending and accessing a packet after user clicks the "Done with this HIT" button. 

### ISSUE THREAD

**Issue by khgkim** [facebookresearch/ParlAI#963]
Question is similar to this post: #794 

Basically I've been trying to pass the value of an input box that is displayed after the user clicks the "**Done**" button. I'm sending a packet (`send_packet`) with the input's value when the user clicks the "**Done with this HIT**" button but I don't know where to call the `act` function in the python side to access the dict passed by the packet. I'm pretty sure that I need to receive the packet in **agents.py**'s `wait_for_hit_completion` since I need to wait until the user inputs a value then clicks the "**Done with this HIT**" button, but it is not receiving the packet. Any ideas on this issue? 

Thanks in advance!

**Comment by JackUrb** [comment]
The **Done with this HIT** button causes the socket to close in anticipation of the page change happening, as we anticipate that it's only ever shown when the world has already set `episode_done` (and is therefore finished collecting data). Rather than rely on an action triggering on that button press, you can create a new button that sends an `act` to the ParlAI world, and then the world can set `episode_done` to true _after_ this message is received.

**Comment by khgkim** [comment]
Hey @JackUrb thanks for the help! 

So I created a new button (appears after user clicks on "Done" button and before clicking "Done with this HIT" button) that calls `send_packet` when clicked, but I'm receiving the previous "Done" button packet (`{'text': "I am done with the chat and clicked the 'Done' button, thank you!", ...}`) instead of the new packet that I'm calling. Any idea why this is happening? Thanks again!
