### ISSUE TITLE
ImportError: No module named 'parlai'

### ISSUE THREAD

**Issue by bittlingmayer** [facebookresearch/ParlAI#98]
I assume __init__.py or setup.py issues:

```
python examples/drqa/train.py -t "#opensubtitles" -bs 32
Traceback (most recent call last):
  File "examples/drqa/train.py", line 28, in <module>
    from parlai.agents.drqa.agents import SimpleDictionaryAgent
ImportError: No module named 'parlai'
```

Similar to https://github.com/facebookresearch/ParlAI/issues/50.

**Comment by ajfisch** [comment]
Hi,
It appears that `parlai` was not properly added to your sys.path. Did you run `python setup.py develop`? 

Or did you run `setup.sh`? That might not work if you have aliases the `python` command. For example, if you have python as an alias to anaconda (instead of having ~/anaconda/bin/python in your PATH) then parlai would have been installed as a package in the default /usr/bin/python instead.

**Comment by bittlingmayer** [comment]
Yes, that was it - had to add it to PYTHONPATH.

Not sure what went wrong.  (I do not use Anaconda.)
